name: Build & Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/openverse-media:latest .

    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/openverse-media:latest

    - name: Setup SSH Key from base64
      run: |
        echo "${{ secrets.EC2_SSH_KEY_B64 }}" | base64 -d > key.pem
        chmod 600 key.pem

    - name: Deploy on EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF
          docker pull ${{ secrets.DOCKER_USERNAME }}/openverse-media:latest
          docker stop openverse-container || true
          docker rm openverse-container || true
          docker run -d --name openverse-container -p 8000:8000 ${{ secrets.DOCKER_USERNAME }}/openverse-media:latest
        EOF

    - name: Cleanup key
      run: rm -f key.pem
